const plants = [
    // Regular Plants
    {
      id: "1",
      name: "Rose",
      sunlight: "Full Sun",
      water: "Every 2-3 days",
      fertilizer: "Every 2 weeks",
      description: "Roses are fragrant flowers that require full sunlight and regular watering to thrive. They are widely used in gardens and bouquets due to their vibrant colors and elegant appearance.",
      image: "/images/rose.jpg",
      temperature: "18-26°C (65-80°F)",
      soil: "Well-drained, loamy soil",
      growthTime: "8-12 weeks",
      uses: "Ornamental, perfume, medicine",
      pests: "Aphids, black spot, powdery mildew",
      propagation: "Cuttings, grafting",
    },
    {
      id: "2",
      name: "Basil",
      sunlight: "Full Sun",
      water: "Daily",
      fertilizer: "Every 3 weeks",
      description: "Basil is a popular herb with aromatic leaves used in cooking. It thrives in warm temperatures and needs regular pruning to encourage bushy growth.",
      image: "/images/basil.jpeg",
      temperature: "20-30°C (68-86°F)",
      soil: "Moist, well-drained soil",
      growthTime: "6-8 weeks",
      uses: "Culinary, medicinal, aromatic",
      pests: "Aphids, spider mites, fungal diseases",
      propagation: "Seeds, cuttings",
    },
    {
      id: "3",
      name: "Cactus",
      sunlight: "Bright, Indirect",
      water: "Every 2 weeks",
      fertilizer: "Once a month",
      description: "Cacti are drought-resistant plants that store water in their stems. They are perfect for dry climates and require minimal maintenance.",
      image: "/images/cactus.jpg",
      temperature: "15-35°C (59-95°F)",
      soil: "Sandy, well-drained soil",
      growthTime: "1-3 years",
      uses: "Ornamental, medicinal, landscaping",
      pests: "Mealybugs, scale insects",
      propagation: "Seeds, cuttings, offsets",
    },
    {
      id: "4",
      name: "Snake Plant",
      sunlight: "Low to Bright Indirect",
      water: "Every 2 weeks",
      fertilizer: "Once every 2 months",
      description: "Snake plants are hardy, air-purifying indoor plants that require minimal care. They can survive in low light and thrive on neglect.",
      image: "/images/snakeplant.jpg",
      temperature: "15-30°C (59-86°F)",
      soil: "Well-drained, sandy soil",
      growthTime: "6-12 months",
      uses: "Indoor air purifier, decorative",
      pests: "Spider mites, fungal infections",
      propagation: "Leaf cuttings, division",
    },
  
    // 🌸 Spring Plants
    { 
      id: "5", 
      name: "Tulip", 
      sunlight: "Full Sun", 
      water: "Twice a week", 
      fertilizer: "Every 2 weeks", 
      description: "Tulips are vibrant flowers that bloom in the spring. They require full sun and moderate watering for healthy growth.", 
      image: "/images/tulip.jpg",
      temperature: "15-20°C (59-68°F)",
      soil: "Well-drained, sandy or loamy soil",
      growthTime: "8-12 weeks",
      uses: "Ornamental gardens, bouquets, decorations",
      pests: "Aphids, slugs, fungal diseases",
      propagation: "Bulbs"
    },
    { 
      id: "6", 
      name: "Daffodil", 
      sunlight: "Full Sun", 
      water: "Once a week", 
      fertilizer: "Every 3 weeks", 
      description: "Daffodils are beautiful spring flowers that thrive in well-drained soil. They require full sunlight to bloom.", 
      image: "/images/daffodil.jpg",
      temperature: "10-18°C (50-65°F)",
      soil: "Sandy or loamy soil with good drainage",
      growthTime: "6-12 weeks",
      uses: "Gardens, flower beds, cut flowers",
      pests: "Narcissus fly, bulb rot",
      propagation: "Bulbs, division"
    },
    { 
      id: "7", 
      name: "Cherry Blossom", 
      sunlight: "Full Sun", 
      water: "Moderate", 
      fertilizer: "Monthly", 
      description: "Cherry blossoms are iconic trees that bloom with pink and white flowers in spring. They need moderate watering and full sunlight.", 
      image: "/images/cherry-blossom.jpg",
      temperature: "15-25°C (59-77°F)",
      soil: "Well-drained, loamy soil",
      growthTime: "3-5 years for full bloom",
      uses: "Ornamental trees, cultural festivals, tea flavoring",
      pests: "Aphids, caterpillars, cherry leaf spot",
      propagation: "Seeds, grafting"
    },
    { 
      id: "8", 
      name: "Hyacinth", 
      sunlight: "Partial Sun", 
      water: "Regular", 
      fertilizer: "Every 2 weeks", 
      description: "Hyacinths are highly fragrant spring flowers that need partial sunlight and regular watering.", 
      image: "/images/hyacinth.jpg",
      temperature: "10-15°C (50-59°F)",
      soil: "Well-drained, fertile soil",
      growthTime: "6-8 weeks",
      uses: "Gardens, indoor decoration, perfume extraction",
      pests: "Bulb mites, fungal infections",
      propagation: "Bulbs"
    },
  
    // ☀ Summer Plants
    { 
      id: "9", 
      name: "Sunflower", 
      sunlight: "Full Sun", 
      water: "Daily", 
      fertilizer: "Every 3 weeks", 
      description: "Sunflowers grow best in full sunlight. Their bright yellow petals follow the sun's direction throughout the day.", 
      image: "/images/sunflower.jpg",
      temperature: "20-30°C (68-86°F)",
      soil: "Well-drained, sandy or loamy soil",
      growthTime: "70-100 days",
      uses: "Oil production, bird feed, ornamental gardens",
      pests: "Aphids, sunflower beetles, downy mildew",
      propagation: "Seeds"
    },
    { 
      id: "10", 
      name: "Marigold", 
      sunlight: "Full Sun", 
      water: "Every 2 days", 
      fertilizer: "Every 4 weeks", 
      description: "Marigolds are easy-to-grow summer flowers that add vibrant color to gardens. They require minimal care and are drought-resistant.", 
      image: "/images/marigold.jpeg",
      temperature: "18-27°C (64-81°F)",
      soil: "Well-drained, slightly acidic soil",
      growthTime: "8-10 weeks",
      uses: "Gardens, pest control, traditional medicine",
      pests: "Spider mites, leaf spot, powdery mildew",
      propagation: "Seeds"
    },
    { 
      id: "11", 
      name: "Lavender", 
      sunlight: "Full Sun", 
      water: "Once a week", 
      fertilizer: "Every 6 weeks", 
      description: "Lavender is a fragrant herb known for its calming scent. It thrives in dry, warm climates with minimal watering.", 
      image: "/images/lavender.jpg",
      temperature: "15-30°C (59-86°F)",
      soil: "Sandy, well-drained soil with alkaline pH",
      growthTime: "2-3 months",
      uses: "Aromatherapy, herbal medicine, essential oils",
      pests: "Aphids, root rot, fungal infections",
      propagation: "Cuttings, seeds"
    },
    { 
      id: "12", 
      name: "Zinnia", 
      sunlight: "Full Sun", 
      water: "Moderate", 
      fertilizer: "Every 3 weeks", 
      description: "Zinnias are bright, long-lasting flowers that bloom throughout summer. They attract butterflies and bees to gardens.", 
      image: "/images/zinnia.jpg",
      temperature: "20-28°C (68-82°F)",
      soil: "Well-drained, rich soil",
      growthTime: "6-8 weeks",
      uses: "Gardens, floral arrangements, pollinator attraction",
      pests: "Aphids, caterpillars, powdery mildew",
      propagation: "Seeds"
    },
  
    // 🍂 Fall Plants
    { 
      id: "13", 
      name: "Chrysanthemum", 
      sunlight: "Partial Sun", 
      water: "Regular", 
      fertilizer: "Monthly", 
      description: "Chrysanthemums, commonly called mums, are classic fall flowers that bloom in various colors.", 
      image: "/images/chrysanthemum.jpg",
      temperature: "10-21°C (50-70°F)",
      soil: "Well-drained, loamy or sandy soil",
      growthTime: "8-12 weeks",
      uses: "Ornamental gardens, floral arrangements, medicinal tea",
      pests: "Aphids, spider mites, powdery mildew",
      propagation: "Cuttings, division"
    },
    { 
      id: "14", 
      name: "Aster", 
      sunlight: "Full Sun", 
      water: "Every 3 days", 
      fertilizer: "Every 2 months", 
      description: "Asters bloom in late summer and fall, providing colorful flowers that attract pollinators.", 
      image: "/images/aster.jpg",
      temperature: "15-25°C (59-77°F)",
      soil: "Well-drained, moist, loamy soil",
      growthTime: "4-6 weeks",
      uses: "Wildflower gardens, pollinator attraction, floral arrangements",
      pests: "Leaf miners, aphids, powdery mildew",
      propagation: "Seeds, division"
    },
    { 
      id: "15", 
      name: "Goldenrod", 
      sunlight: "Full Sun", 
      water: "Moderate", 
      fertilizer: "Monthly", 
      description: "Goldenrod is a bright yellow wildflower that thrives in sunny locations.", 
      image: "/images/goldenrod.jpg",
      temperature: "18-27°C (64-81°F)",
      soil: "Well-drained, sandy or clay soil",
      growthTime: "6-8 weeks",
      uses: "Wildlife habitat, pollinator attraction, medicinal purposes",
      pests: "Rust fungi, leafhoppers, powdery mildew",
      propagation: "Seeds, rhizome division"
    },
    { 
      id: "16", 
      name: "Sedum", 
      sunlight: "Partial Sun", 
      water: "Low", 
      fertilizer: "Every 3 months", 
      description: "Sedum is a low-maintenance plant that thrives in dry conditions and is perfect for fall gardens.", 
      image: "/images/sedum.jpg",
      temperature: "10-24°C (50-75°F)",
      soil: "Well-drained, sandy or rocky soil",
      growthTime: "6-10 weeks",
      uses: "Rock gardens, green roofs, ground cover",
      pests: "Aphids, mealybugs, root rot",
      propagation: "Stem cuttings, division"
    },
  
    // ❄ Winter Plants
    { 
      id: "17", 
      name: "Camellia", 
      sunlight: "Partial Sun", 
      water: "Regular", 
      fertilizer: "Every 3 months", 
      description: "Camellias bloom in the colder months, bringing color to winter gardens.", 
      image: "/images/camellia.jpg",
      temperature: "7-18°C (45-65°F)",
      soil: "Acidic, well-drained, moist soil",
      growthTime: "6-12 months",
      uses: "Ornamental gardening, tea production (Camellia sinensis)",
      pests: "Scale insects, aphids, root rot",
      propagation: "Seed, semi-hardwood cuttings, grafting"
    },
    { 
      id: "18", 
      name: "Hellebore", 
      sunlight: "Partial Shade", 
      water: "Low", 
      fertilizer: "Every 2 months", 
      description: "Hellebores, or Lenten roses, are frost-resistant flowers that bloom in late winter.", 
      image: "/images/hellebore.jpg",
      temperature: "-5 to 15°C (23-59°F)",
      soil: "Well-drained, rich, slightly alkaline soil",
      growthTime: "6-8 months",
      uses: "Ornamental gardens, shade plantings, medicinal uses",
      pests: "Aphids, black spot, fungal diseases",
      propagation: "Division, seeds"
    },
    { 
      id: "19", 
      name: "Winter Jasmine", 
      sunlight: "Full Sun", 
      water: "Every 3 days", 
      fertilizer: "Every 4 weeks", 
      description: "Winter jasmine blooms with bright yellow flowers, adding color to the winter season.", 
      image: "/images/winter-jasmine.jpg",
      temperature: "-10 to 15°C (14-59°F)",
      soil: "Well-drained, loamy soil",
      growthTime: "6-9 months",
      uses: "Trellis climber, ground cover, winter blooms",
      pests: "Aphids, spider mites, scale insects",
      propagation: "Cuttings, layering"
    },
    { 
      id: "20", 
      name: "Holly", 
      sunlight: "Full Sun", 
      water: "Moderate", 
      fertilizer: "Every 3 months", 
      description: "Holly is a festive winter plant known for its red berries and deep green leaves.", 
      image: "/images/holly.jpg",
      temperature: "-5 to 10°C (23-50°F)",
      soil: "Well-drained, slightly acidic soil",
      growthTime: "1-2 years",
      uses: "Christmas decorations, hedging, wildlife attraction",
      pests: "Leaf miners, scale insects, holly leaf blight",
      propagation: "Seeds, semi-hardwood cuttings"
    },
  
    // 🍅 Vegetable Plants
    { 
      id: "21", 
      name: "Tomato", 
      sunlight: "Full Sun", 
      water: "Daily", 
      fertilizer: "Every 2 weeks", 
      description: "Tomatoes grow best in warm weather and require daily watering to keep their soil moist.", 
      image: "/images/tomato.jpg",
      temperature: "18-27°C (65-80°F)",
      soil: "Well-drained, loamy soil",
      growthTime: "60-90 days",
      uses: "Cooking, salads, sauces, juices",
      pests: "Aphids, whiteflies, hornworms",
      propagation: "Seeds, cuttings"
    },
    { 
      id: "22", 
      name: "Carrot", 
      sunlight: "Full Sun", 
      water: "Every 2 days", 
      fertilizer: "Every 3 weeks", 
      description: "Carrots are root vegetables that thrive in loose, sandy soil and need consistent moisture.", 
      image: "/images/carrot.jpeg",
      temperature: "10-24°C (50-75°F)",
      soil: "Loose, well-drained sandy soil",
      growthTime: "70-80 days",
      uses: "Raw consumption, soups, juices, salads",
      pests: "Carrot rust fly, aphids",
      propagation: "Seeds"
    },
    { 
      id: "23", 
      name: "Cucumber", 
      sunlight: "Full Sun", 
      water: "Daily", 
      fertilizer: "Every 3 weeks", 
      description: "Cucumbers are vining vegetables that require support and regular watering.", 
      image: "/images/cucumber.jpg",
      temperature: "18-30°C (65-85°F)",
      soil: "Well-drained, rich loamy soil",
      growthTime: "50-70 days",
      uses: "Salads, pickles, skincare",
      pests: "Cucumber beetles, powdery mildew",
      propagation: "Seeds"
    },
    { 
      id: "24", 
      name: "Spinach", 
      sunlight: "Partial Sun", 
      water: "Every 2 days", 
      fertilizer: "Every 4 weeks", 
      description: "Spinach grows well in cool temperatures and needs well-drained soil.", 
      image: "/images/spinach.jpg",
      temperature: "7-24°C (45-75°F)",
      soil: "Well-drained, nutrient-rich soil",
      growthTime: "40-50 days",
      uses: "Salads, cooking, smoothies",
      pests: "Leaf miners, aphids, downy mildew",
      propagation: "Seeds"
    },
    { 
      id: "25", 
      name: "Bell Pepper", 
      sunlight: "Full Sun", 
      water: "Every 2 days", 
      fertilizer: "Every 3 weeks", 
      description: "Bell peppers require warm weather and consistent watering to prevent drying out.", 
      image: "/images/bellpepper.jpg",
      temperature: "20-27°C (68-80°F)",
      soil: "Well-drained, loamy soil",
      growthTime: "60-90 days",
      uses: "Cooking, salads, stuffing",
      pests: "Aphids, spider mites, bacterial spot",
      propagation: "Seeds"
    },
    { 
      id: "26", 
      name: "Eggplant", 
      sunlight: "Full Sun", 
      water: "Every 3 days", 
      fertilizer: "Every 2 weeks", 
      description: "Eggplants are heat-loving vegetables that need rich soil and moderate watering.", 
      image: "/images/eggplant.jpg",
      temperature: "21-30°C (70-85°F)",
      soil: "Well-drained, sandy loam",
      growthTime: "100-150 days",
      uses: "Cooking, frying, grilling",
      pests: "Flea beetles, aphids, spider mites",
      propagation: "Seeds"
    },
    { 
      id: "27", 
      name: "Broccoli", 
      sunlight: "Full Sun", 
      water: "Every 3 days", 
      fertilizer: "Every 4 weeks", 
      description: "Broccoli is a cool-season vegetable that requires consistent watering for proper growth.", 
      image: "/images/broccoli.jpg",
      temperature: "13-24°C (55-75°F)",
      soil: "Well-drained, rich loamy soil",
      growthTime: "70-100 days",
      uses: "Stir-fries, steaming, salads",
      pests: "Cabbage worms, aphids",
      propagation: "Seeds"
    },
    { 
      id: "28", 
      name: "Lettuce", 
      sunlight: "Partial Sun", 
      water: "Daily", 
      fertilizer: "Every 3 weeks", 
      description: "Lettuce grows quickly and prefers moist soil in cooler temperatures.", 
      image: "/images/lettuce.jpg",
      temperature: "7-20°C (45-68°F)",
      soil: "Well-drained, sandy loam",
      growthTime: "30-60 days",
      uses: "Salads, sandwiches, wraps",
      pests: "Aphids, slugs, downy mildew",
      propagation: "Seeds"
    },
    { 
      id: "29", 
      name: "Pumpkin", 
      sunlight: "Full Sun", 
      water: "Every 2 days", 
      fertilizer: "Every 3 weeks", 
      description: "Pumpkins require a lot of space and warm temperatures to grow well.", 
      image: "/images/pumpkin.jpeg",
      temperature: "18-32°C (65-90°F)",
      soil: "Well-drained, rich loamy soil",
      growthTime: "90-120 days",
      uses: "Pies, soups, decoration",
      pests: "Squash bugs, vine borers",
      propagation: "Seeds"
    },
    { 
      id: "30", 
      name: "Radish", 
      sunlight: "Full Sun", 
      water: "Daily", 
      fertilizer: "Every 4 weeks", 
      description: "Radishes grow quickly and are great for early spring and fall gardening.", 
      image: "/images/radish.jpg",
      temperature: "10-24°C (50-75°F)",
      soil: "Well-drained, sandy soil",
      growthTime: "25-40 days",
      uses: "Salads, pickling, roasting",
      pests: "Flea beetles, root maggots",
      propagation: "Seeds"
    },
    { 
      id: "31", 
      name: "Zucchini", 
      sunlight: "Full Sun", 
      water: "Every 3 days", 
      fertilizer: "Every 3 weeks", 
      description: "Zucchinis are productive plants that need plenty of sun and space to spread.", 
      image: "/images/zucchini.jpg",
      temperature: "20-30°C (68-86°F)",
      soil: "Well-drained, loamy soil",
      growthTime: "45-55 days",
      uses: "Stir-fries, baking, grilling",
      pests: "Squash bugs, powdery mildew",
      propagation: "Seeds"
    },
    { 
      id: "32", 
      name: "Onion", 
      sunlight: "Full Sun", 
      water: "Every 4 days", 
      fertilizer: "Every 4 weeks", 
      description: "Onions need well-drained soil and regular watering for proper bulb growth.", 
      image: "/images/onion.jpg",
      temperature: "13-25°C (55-77°F)",
      soil: "Well-drained, loose soil",
      growthTime: "80-150 days",
      uses: "Cooking, pickling, seasoning",
      pests: "Onion maggots, thrips",
      propagation: "Seeds, sets"
    },
    { 
      id: "33", 
      name: "Garlic", 
      sunlight: "Full Sun", 
      water: "Every 7 days", 
      fertilizer: "Every 6 weeks", 
      description: "Garlic grows best in cooler weather and requires minimal watering.", 
      image: "/images/garlic.jpg",
      temperature: "10-21°C (50-70°F)",
      soil: "Well-drained, sandy loam",
      growthTime: "90-180 days",
      uses: "Cooking, medicine, seasoning",
      pests: "White rot, onion thrips",
      propagation: "Cloves"
    },
    { 
      id: "34", 
      name: "Corn", 
      sunlight: "Full Sun", 
      water: "Daily", 
      fertilizer: "Every 2 weeks", 
      description: "Corn needs plenty of sun, space, and frequent watering for high yields.", 
      image: "/images/corn.jpg",
      temperature: "18-32°C (65-90°F)",
      soil: "Well-drained, loamy soil",
      growthTime: "60-100 days",
      uses: "Cooking, flour, livestock feed",
      pests: "Corn earworms, armyworms",
      propagation: "Seeds"
    },
    { 
      id: "35", 
      name: "Sweet Potato", 
      sunlight: "Full Sun", 
      water: "Every 3 days", 
      fertilizer: "Every 4 weeks", 
      description: "Sweet potatoes thrive in warm climates and need loose, sandy soil.", 
      image: "/images/sweetpotato.jpeg",
      temperature: "21-30°C (70-86°F)",
      soil: "Sandy, well-drained soil",
      growthTime: "90-120 days",
      uses: "Cooking, baking, chips",
      pests: "Sweet potato weevils, root rot",
      propagation: "Slips (vine cuttings)"
    },
    { 
      id: "36", 
      name: "Cabbage", 
      sunlight: "Full Sun", 
      water: "Every 2 days", 
      fertilizer: "Every 3 weeks", 
      description: "Cabbages need cool temperatures and consistent moisture.", 
      image: "/images/cabbage.jpg",
      temperature: "7-24°C (45-75°F)",
      soil: "Well-drained, fertile soil",
      growthTime: "60-100 days",
      uses: "Salads, cooking, pickling",
      pests: "Cabbage worms, aphids",
      propagation: "Seeds"
    },
    { 
      id: "37", 
      name: "Beetroot", 
      sunlight: "Full Sun", 
      water: "Every 3 days", 
      fertilizer: "Every 4 weeks", 
      description: "Beetroots grow best in loose soil and require moderate watering.", 
      image: "/images/beetroot.jpg",
      temperature: "10-24°C (50-75°F)",
      soil: "Well-drained, sandy loam",
      growthTime: "55-70 days",
      uses: "Salads, cooking, juicing",
      pests: "Leaf miners, aphids",
      propagation: "Seeds"
    },
    { 
      id: "38", 
      name: "Kale", 
      sunlight: "Full Sun", 
      water: "Every 3 days", 
      fertilizer: "Every 4 weeks", 
      description: "Kale is a nutrient-rich leafy green that thrives in cool weather.", 
      image: "/images/kale.jpg",
      temperature: "5-25°C (41-77°F)",
      soil: "Well-drained, loamy soil",
      growthTime: "50-70 days",
      uses: "Salads, smoothies, soups",
      pests: "Aphids, cabbage worms",
      propagation: "Seeds"
    },
    { 
      id: "39", 
      name: "Peas", 
      sunlight: "Partial Sun", 
      water: "Every 2 days", 
      fertilizer: "Every 3 weeks", 
      description: "Peas prefer cooler temperatures and need support for climbing.", 
      image: "/images/peas.jpg",
      temperature: "7-21°C (45-70°F)",
      soil: "Well-drained, loamy soil",
      growthTime: "60-90 days",
      uses: "Soups, salads, cooking",
      pests: "Aphids, pea weevils",
      propagation: "Seeds"
    },
    { 
      id: "40", 
      name: "Cauliflower", 
      sunlight: "Full Sun", 
      water: "Every 2 days", 
      fertilizer: "Every 3 weeks", 
      description: "Cauliflower needs consistent moisture and cool temperatures.", 
      image: "/images/cauliflower.jpg",
      temperature: "13-24°C (55-75°F)",
      soil: "Well-drained, loamy soil",
      growthTime: "55-100 days",
      uses: "Cooking, rice substitute, pickling",
      pests: "Cabbage worms, aphids",
      propagation: "Seeds"
    },
  
    // 🍎 Fruit Plants
    { 
      id: "41", 
      name: "Apple", 
      sunlight: "Full Sun", 
      water: "Every 3 days", 
      fertilizer: "Every 2 months", 
      description: "Apple trees require full sunlight and well-drained soil. They produce sweet, nutritious fruits.", 
      image: "/images/apple.jpg",
      temperature: "18-24°C (64-75°F)",
      soil: "Loamy, well-drained soil",
      growthTime: "2-5 years",
      uses: "Fresh eating, juicing, baking",
      pests: "Codling moths, apple scab",
      propagation: "Grafting, seeds"
    },
    { 
      id: "42", 
      name: "Banana", 
      sunlight: "Full Sun", 
      water: "Daily", 
      fertilizer: "Every 6 weeks", 
      description: "Banana plants thrive in tropical climates and need regular watering.", 
      image: "/images/banana.jpg",
      temperature: "24-30°C (75-86°F)",
      soil: "Rich, well-drained soil",
      growthTime: "9-12 months",
      uses: "Fresh eating, smoothies, baking",
      pests: "Banana weevils, nematodes",
      propagation: "Rhizomes (suckers)"
    },
    { 
      id: "43", 
      name: "Mango", 
      sunlight: "Full Sun", 
      water: "Every 4 days", 
      fertilizer: "Every 2 months", 
      description: "Mango trees require warm temperatures and well-drained soil.", 
      image: "/images/mango.jpg",
      temperature: "24-35°C (75-95°F)",
      soil: "Loamy, well-drained soil",
      growthTime: "3-5 years",
      uses: "Juices, desserts, pickles",
      pests: "Fruit flies, anthracnose",
      propagation: "Grafting, seeds"
    },
    { 
      id: "44", 
      name: "Strawberry", 
      sunlight: "Full Sun", 
      water: "Daily", 
      fertilizer: "Every 3 weeks", 
      description: "Strawberries are small fruits that grow best in cool temperatures.", 
      image: "/images/strawberry.jpeg",
      temperature: "15-25°C (59-77°F)",
      soil: "Sandy loam, rich in organic matter",
      growthTime: "4-6 months",
      uses: "Fresh eating, jams, smoothies",
      pests: "Spider mites, powdery mildew",
      propagation: "Runners, seeds"
    },
    { 
      id: "45", 
      name: "Pineapple", 
      sunlight: "Full Sun", 
      water: "Every 5 days", 
      fertilizer: "Every 2 months", 
      description: "Pineapple plants need well-drained soil and warm temperatures.", 
      image: "/images/pineapple.jpg",
      temperature: "21-32°C (70-90°F)",
      soil: "Well-drained sandy loam",
      growthTime: "16-24 months",
      uses: "Juices, desserts, fresh eating",
      pests: "Mealybugs, fungal rot",
      propagation: "Crown cuttings, suckers"
    },
    { 
      id: "46", 
      name: "Orange", 
      sunlight: "Full Sun", 
      water: "Every 3 days", 
      fertilizer: "Every 3 months", 
      description: "Orange trees produce juicy citrus fruits and need regular watering.", 
      image: "/images/orange.jpg",
      temperature: "22-32°C (72-90°F)",
      soil: "Well-drained, sandy soil",
      growthTime: "2-3 years",
      uses: "Juicing, fresh eating, marmalade",
      pests: "Aphids, citrus canker",
      propagation: "Grafting, seeds"
    },
    { 
      id: "47", 
      name: "Watermelon", 
      sunlight: "Full Sun", 
      water: "Daily", 
      fertilizer: "Every 3 weeks", 
      description: "Watermelon plants grow best in warm climates with plenty of space.", 
      image: "/images/watermelon.jpg",
      temperature: "22-30°C (72-86°F)",
      soil: "Sandy, well-drained soil",
      growthTime: "80-100 days",
      uses: "Juices, fresh eating, fruit salads",
      pests: "Cucumber beetles, aphids",
      propagation: "Seeds"
    },
    { 
      id: "48", 
      name: "Grapes", 
      sunlight: "Full Sun", 
      water: "Every 3 days", 
      fertilizer: "Every 2 months", 
      description: "Grapevines require trellising and full sunlight to produce sweet fruits.", 
      image: "/images/grapes.jpg",
      temperature: "18-25°C (64-77°F)",
      soil: "Well-drained, sandy loam",
      growthTime: "2-3 years",
      uses: "Wine, fresh eating, raisins",
      pests: "Grape leafhoppers, powdery mildew",
      propagation: "Cuttings"
    },
    { 
      id: "49", 
      name: "Papaya", 
      sunlight: "Full Sun", 
      water: "Every 4 days", 
      fertilizer: "Every 6 weeks", 
      description: "Papaya trees thrive in tropical weather and require moist soil.", 
      image: "/images/papaya.jpg",
      temperature: "25-35°C (77-95°F)",
      soil: "Well-drained, sandy loam",
      growthTime: "6-12 months",
      uses: "Smoothies, fresh eating, cooking",
      pests: "Papaya mealybugs, anthracnose",
      propagation: "Seeds"
    },
    { 
      id: "50", 
      name: "Avocado", 
      sunlight: "Full Sun", 
      water: "Every 5 days", 
      fertilizer: "Every 2 months", 
      description: "Avocado trees need warm weather and well-drained soil.", 
      image: "/images/avocado.jpg",
      temperature: "20-30°C (68-86°F)",
      soil: "Loamy, well-drained soil",
      growthTime: "3-4 years",
      uses: "Guacamole, salads, spreads",
      pests: "Root rot, spider mites",
      propagation: "Grafting, seeds"
    },

    // ✅ *Newly Added - Fruit Plants*
  { 
    id: "51", 
    name: "Peach", 
    sunlight: "Full Sun", 
    water: "Every 2-3 days", 
    fertilizer: "Every 4-6 weeks", 
    description: "Peach trees produce juicy fruits and require full sun and well-drained soil.", 
    image: "/images/peach.jpg",
    temperature: "18-30°C (65-85°F)",
    soil: "Well-drained, sandy loam",
    growth: "3-5 years to bear fruit",
    common: "Eaten fresh, used in desserts, jams",
    pests: "Aphids, fruit flies, peach leaf curl",
    propagation: "Seeds, grafting"
  },
  { 
    id: "52", 
    name: "Pear", 
    sunlight: "Full Sun", 
    water: "Every 4-5 days", 
    fertilizer: "Every 6 weeks", 
    description: "Pears grow best in well-drained soil with consistent watering and pruning.", 
    image: "/images/pear.jpg",
    temperature: "15-25°C (59-77°F)",
    soil: "Loamy, well-drained",
    growth: "4-6 years to bear fruit",
    uses: "Eaten fresh, canned, dried, used in salads",
    pests: "Codling moth, fire blight, aphids",
    propagation: "Grafting, cuttings"
  },
  { 
    id: "53", 
    name: "Pomegranate", 
    sunlight: "Full Sun", 
    water: "Every 5-7 days", 
    fertilizer: "Every 3 months", 
    description: "Pomegranates thrive in warm climates and require occasional deep watering.", 
    image: "/images/pomegranate.jpg",
    temperature: "25-35°C (77-95°F)",
    soil: "Well-drained, sandy or loamy",
    growth: "3-4 years to bear fruit",
    uses: "Eaten fresh, juiced, used in sauces",
    pests: "Aphids, whiteflies, pomegranate butterfly",
    propagation: "Seeds, cuttings, air layering"
  },

  // ✅ *Newly Added - Vegetable Plants*
  { 
    id: "54", 
    name: "Brussels Sprouts", 
    sunlight: "Full Sun", 
    water: "Every 2-3 days", 
    fertilizer: "Every 4 weeks", 
    description: "Brussels sprouts grow best in cool temperatures with rich, fertile soil.", 
    image: "/images/brussels-sprouts.jpg",
    temperature: "7-23°C (45-75°F)",
    soil: "Moist, well-drained, slightly acidic",
    growth: "90-120 days",
    uses: "Steamed, roasted, stir-fried",
    pests: "Cabbage worms, aphids, flea beetles",
    propagation: "Seeds, transplants"
  },
  { 
    id: "55", 
    name: "Kale", 
    sunlight: "Full Sun", 
    water: "Every 3 days", 
    fertilizer: "Every 4 weeks", 
    description: "Kale is a nutrient-rich leafy green that thrives in cool weather.", 
    image: "/images/kale.jpg",
    temperature: "4-25°C (40-77°F)",
    soil: "Well-drained, rich in organic matter",
    growth: "55-75 days",
    uses: "Salads, smoothies, soups",
    pests: "Aphids, cabbage worms, flea beetles",
    propagation: "Seeds, transplants"
  },
//aquaplants

{ 
    id: "56", 
    name: "Water Hyacinth", 
    sunlight: "Full Sun to Partial Shade", 
    water: "Fully submerged", 
    fertilizer: "Every 4 weeks", 
    description: "Water hyacinths are floating plants known for their lavender flowers. They help oxygenate water and reduce algae growth.", 
    idealTemperature: "20-30°C (68-86°F)", 
    soil: "Not required (free-floating)", 
    growthTime: "Rapid growth", 
    uses: "Water filtration, decorative ponds", 
    pests: "Watch out for overgrowth, can become invasive", 
    propagation: "Offsets and daughter plants", 
    image: "/images/water-hyacinth.jpg" 
  },

  { 
    id: "57", 
    name: "Anubias", 
    sunlight: "Low to Medium Light", 
    water: "Fully submerged", 
    fertilizer: "Every 6 weeks", 
    description: "Anubias is a slow-growing aquatic plant that thrives in freshwater aquariums.", 
    idealTemperature: "22-28°C (72-82°F)", 
    soil: "Aquarium gravel or attached to driftwood", 
    growthTime: "Slow-growing", 
    uses: "Aquariums, decorative tanks", 
    pests: "Rare, but susceptible to algae buildup", 
    propagation: "Rhizome division", 
    image: "/images/anubias.jpg" 
  },

  { 
    id: "58", 
    name: "Java Fern", 
    sunlight: "Low to Medium Light", 
    water: "Fully submerged", 
    fertilizer: "Every 6 weeks", 
    description: "Java fern is a hardy aquatic plant that grows well in freshwater tanks and requires minimal care.", 
    idealTemperature: "20-28°C (68-82°F)", 
    soil: "No soil needed (can attach to rocks or driftwood)", 
    growthTime: "Slow-growing", 
    uses: "Aquariums, low-maintenance tanks", 
    pests: "Rare, can develop brown spots if exposed to too much light", 
    propagation: "Rhizome division and adventitious plantlets", 
    image: "/images/java-fern.jpg" 
  },

  { 
    id: "59", 
    name: "Amazon Sword", 
    sunlight: "Medium to High Light", 
    water: "Fully submerged", 
    fertilizer: "Every 4 weeks", 
    description: "A popular aquarium plant with large green leaves that provides shelter for fish.", 
    idealTemperature: "22-28°C (72-82°F)", 
    soil: "Nutrient-rich aquarium substrate", 
    growthTime: "Moderate to fast", 
    uses: "Aquariums, fish breeding tanks", 
    pests: "Susceptible to iron deficiency, causing yellowing leaves", 
    propagation: "Runner shoots", 
    image: "/images/amazon-sword.jpg" 
  },

  { 
    id: "60", 
    name: "Duckweed", 
    sunlight: "Full Sun to Partial Shade", 
    water: "Floating on water surface", 
    fertilizer: "Minimal, absorbs nutrients from water", 
    description: "Duckweed is a fast-growing floating plant that helps reduce algae and improve water quality.", 
    idealTemperature: "15-30°C (59-86°F)", 
    soil: "Not required (free-floating)", 
    growthTime: "Very fast", 
    uses: "Water purification, fish food, biofuel production", 
    pests: "Overgrowth can block light for other aquatic plants", 
    propagation: "Vegetative reproduction (rapid spreading)", 
    image: "/images/duckweed.jpg" 
  },
  { 
    id: "61", 
    name: "Lotus", 
    sunlight: "Full Sun", 
    water: "Fully submerged roots with floating leaves", 
    fertilizer: "Every 2-3 weeks during the growing season", 
    description: "The lotus is a beautiful aquatic plant known for its large, fragrant flowers. It symbolizes purity and spiritual enlightenment in many cultures.", 
    idealTemperature: "20-35°C (68-95°F)", 
    soil: "Clay-rich soil with submerged roots", 
    growthTime: "60-90 days to bloom", 
    uses: "Ponds, religious ceremonies, herbal medicine, food (roots and seeds)", 
    pests: "Watch out for aphids, fungal infections, and caterpillars", 
    propagation: "Seed germination or rhizome division", 
    image: "/images/lotus.jpg" 
  },
{ 
    id: "62", 
    name: "Spider Plant", 
    sunlight: "Indirect Sunlight", 
    water: "Once a week", 
    fertilizer: "Every 4 weeks", 
    description: "Spider plants are easy-to-grow, air-purifying plants with long, arching leaves and baby plantlets.", 
    idealTemperature: "18-27°C (65-80°F)", 
    soil: "Well-draining potting mix", 
    growthTime: "2-3 months to establish", 
    uses: "Air purification, decorative indoor plant", 
    pestsDiseases: "Watch out for spider mites and root rot", 
    propagation: "By baby plantlets or division", 
    image: "/images/spider-plant.jpg" 
  },
  { 
    id: "63", 
    name: "Peace Lily", 
    sunlight: "Low to Medium Indirect Light", 
    water: "Every 5-7 days", 
    fertilizer: "Every 6 weeks", 
    description: "Peace lilies are elegant plants with white flowers and excellent air-purifying abilities.", 
    idealTemperature: "18-30°C (65-86°F)", 
    soil: "Moist, well-draining soil", 
    growthTime: "3-5 months to bloom", 
    uses: "Air purification, indoor decoration", 
    pestsDiseases: "Watch out for spider mites, brown leaf tips", 
    propagation: "By root division", 
    image: "/images/peace-lily.jpg" 
  },
  { 
    id: "64", 
    name: "Rubber Plant", 
    sunlight: "Bright, Indirect Sunlight", 
    water: "Every 1-2 weeks", 
    fertilizer: "Every 2 months", 
    description: "The rubber plant is a hardy indoor plant with large, glossy leaves that help improve air quality.", 
    idealTemperature: "18-27°C (65-80°F)", 
    soil: "Well-draining potting mix", 
    growthTime: "4-6 months to establish", 
    uses: "Air purification, home and office decor", 
    pestsDiseases: "Watch out for mealybugs and root rot", 
    propagation: "By stem cuttings", 
    image: "/images/rubber-plant.jpg" 
  },
  { 
    id: "65", 
    name: "Elephant Ear Plant", 
    sunlight: "Bright, Indirect Light", 
    water: "Every 3-5 days", 
    fertilizer: "Every 4 weeks", 
    description: "Known for its large, tropical leaves, the Elephant Ear plant adds a bold look to any space.", 
    idealTemperature: "20-32°C (68-90°F)", 
    soil: "Moist, well-drained soil", 
    growthTime: "3-6 months to reach full size", 
    uses: "Indoor decor, tropical garden plant", 
    pestsDiseases: "Watch out for fungal diseases, aphids", 
    propagation: "By bulb division", 
    image: "/images/elephant-ear.jpg" 
  },
  { 
    id: "66", 
    name: "Ferns", 
    sunlight: "Partial Shade to Indirect Light", 
    water: "Every 3-4 days", 
    fertilizer: "Every 6 weeks", 
    description: "Ferns are lush, green plants that thrive in humidity and add a jungle-like feel to interiors.", 
    idealTemperature: "15-25°C (59-77°F)", 
    soil: "Rich, well-draining soil", 
    growthTime: "3-6 months to mature", 
    uses: "Air purification, indoor gardens", 
    pestsDiseases: "Watch out for fungal diseases, scale insects", 
    propagation: "By spores or division", 
    image: "/images/ferns.jpg" 
  },
  { 
    id: "67", 
    name: "Pothos", 
    sunlight: "Low to Bright Indirect Light", 
    water: "Every 1-2 weeks", 
    fertilizer: "Every 4-6 weeks", 
    description: "Pothos is a fast-growing, low-maintenance vine that is perfect for indoor spaces.", 
    idealTemperature: "18-30°C (65-86°F)", 
    soil: "Well-draining potting mix", 
    growthTime: "2-4 months to grow long vines", 
    uses: "Hanging baskets, air purification", 
    pestsDiseases: "Watch out for spider mites, root rot", 
    propagation: "By stem cuttings", 
    image: "/images/pothos.jpg" 
  },
  { 
    id: "68", 
    name: "English Ivy", 
    sunlight: "Bright, Indirect Light", 
    water: "Every 5-7 days", 
    fertilizer: "Every 6 weeks", 
    description: "English Ivy is a beautiful trailing plant that grows well in hanging baskets and walls.", 
    idealTemperature: "15-25°C (59-77°F)", 
    soil: "Well-draining potting mix", 
    growthTime: "2-6 months to establish", 
    uses: "Hanging baskets, green walls", 
    pestsDiseases: "Watch out for spider mites, powdery mildew", 
    propagation: "By stem cuttings", 
    image: "/images/english-ivy.jpg" 
  },
  { 
    id: "69", 
    name: "Succulents & Cacti", 
    sunlight: "Bright, Direct Sunlight", 
    water: "Every 2-3 weeks", 
    fertilizer: "Every 3 months", 
    description: "Succulents and cacti are drought-tolerant plants that store water in their fleshy stems.", 
    idealTemperature: "20-35°C (68-95°F)", 
    soil: "Well-draining cactus soil", 
    growthTime: "3-12 months to mature", 
    uses: "Terrariums, indoor gardens, low-maintenance decor", 
    pestsDiseases: "Watch out for mealybugs, root rot", 
    propagation: "By leaf cuttings or offsets", 
    image: "/images/succulents.jpg" 
  },
  { 
    id: "70", 
    name: "Mint", 
    sunlight: "Partial Sun to Full Sun", 
    water: "Every 2-3 days", 
    fertilizer: "Every 6 weeks", 
    description: "Mint is an aromatic herb with fast-growing stems, perfect for tea, cooking, and freshening up gardens.", 
    idealTemperature: "15-30°C (59-86°F)", 
    soil: "Moist, well-draining soil", 
    growthTime: "3-5 weeks to harvest", 
    uses: "Tea, cooking, insect repellent", 
    pestsDiseases: "Watch out for whiteflies, powdery mildew", 
    propagation: "By cuttings or runners", 
    image: "/images/mint.jpg" 
  },

  // 🍅 Vegetable Plants
  {
    id: "71",
    name: "Green Beans",
    sunlight: "Full Sun",
    water: "Every 2-3 days",
    fertilizer: "Every 3 weeks",
    description: "Green beans are nutritious legumes that grow in bushes or vines, requiring a warm climate.",
    image: "/images/green-beans.jpg",
    temperature: "18-29°C (65-85°F)",
    soil: "Loamy, well-drained",
    growth: "50-65 days",
    uses: "Boiled, stir-fried, soups, salads",
    pests: "Aphids, bean beetles",
    propagation: "Seeds"
  },
  {
    id: "72",
    name: "Okra (Lady's Finger)",
    sunlight: "Full Sun",
    water: "Every 3 days",
    fertilizer: "Every 2 weeks",
    description: "Okra is a warm-season vegetable with high fiber content, widely used in soups and stews.",
    image: "/images/okra.JPG",
    temperature: "22-32°C (72-90°F)",
    soil: "Fertile, loamy soil",
    growth: "50-70 days",
    uses: "Fried, stews, gumbo",
    pests: "Aphids, flea beetles",
    propagation: "Seeds"
  },
  {
    id: "73",
    name: "Turnip",
    sunlight: "Full Sun / Partial Shade",
    water: "Every 3 days",
    fertilizer: "Every 3 weeks",
    description: "Turnips are root vegetables that grow quickly and have a slightly peppery taste.",
    image: "/images/turnip.jpg",
    temperature: "10-20°C (50-68°F)",
    soil: "Loamy, sandy soil",
    growth: "30-60 days",
    uses: "Soups, stews, roasted",
    pests: "Cabbage worms, flea beetles",
    propagation: "Seeds"
  },
  {
    id: "74",
    name: "Asparagus",
    sunlight: "Full Sun",
    water: "Every 3-4 days",
    fertilizer: "Every 4 weeks",
    description: "Asparagus is a perennial vegetable that takes time to establish but produces for years.",
    image: "/images/asparagus.jpg",
    temperature: "16-30°C (60-85°F)",
    soil: "Well-drained, sandy loam",
    growth: "2-3 years for full harvest",
    uses: "Grilled, roasted, soups",
    pests: "Asparagus beetle",
    propagation: "Seeds, root division"
  },
  {
    id: "75",
    name: "Celery",
    sunlight: "Full Sun / Partial Shade",
    water: "Frequent, keep soil moist",
    fertilizer: "Every 3 weeks",
    description: "Celery is a cool-season vegetable grown for its crunchy stalks, commonly used in salads and soups.",
    image: "/images/celery.jpg",
    temperature: "15-24°C (59-75°F)",
    soil: "Rich, well-drained loam",
    growth: "85-120 days",
    uses: "Salads, soups, juicing",
    pests: "Aphids, celery leafminers",
    propagation: "Seeds"
  },
  {
    id: "76",
    name: "Radicchio",
    sunlight: "Full Sun / Partial Shade",
    water: "Every 2 days",
    fertilizer: "Every 3 weeks",
    description: "Radicchio is a red leafy vegetable with a slightly bitter taste, popular in salads.",
    image: "/images/radicchio.jpg",
    temperature: "15-25°C (59-77°F)",
    soil: "Moist, well-drained",
    growth: "60-80 days",
    uses: "Salads, roasted dishes",
    pests: "Slugs, snails, aphids",
    propagation: "Seeds"
  },
  {
    id: "77",
    name: "Artichoke",
    sunlight: "Full Sun",
    water: "Every 3-4 days",
    fertilizer: "Every 4 weeks",
    description: "Artichokes are thistle-like vegetables with edible flower buds, popular in Mediterranean cuisine.",
    image: "/images/artichoke.jpg",
    temperature: "15-25°C (59-77°F)",
    soil: "Well-drained, sandy loam",
    growth: "85-150 days",
    uses: "Boiled, grilled, dips",
    pests: "Aphids, snails, slugs",
    propagation: "Seeds, root division"
  },
  {
    id: "78",
    name: "Swiss Chard",
    sunlight: "Full Sun / Partial Shade",
    water: "Every 3 days",
    fertilizer: "Every 4 weeks",
    description: "Swiss chard is a leafy green vegetable with colorful stalks, rich in vitamins and minerals.",
    image: "/images/swiss-chard.jpg",
    temperature: "10-30°C (50-86°F)",
    soil: "Fertile, well-drained",
    growth: "50-60 days",
    uses: "Salads, stir-fries, soups",
    pests: "Leafminers, aphids",
    propagation: "Seeds"
  },
  // 🍎 Additional Fruit Plants
{
    id: "79",
    name: "Blueberry",
    sunlight: "Full Sun",
    water: "Every 3-4 days",
    fertilizer: "Every 6 weeks",
    description: "Blueberries are nutrient-rich berries that thrive in acidic soil and full sunlight.",
    image: "/images/blueberry.jpg",
    temperature: "13-26°C (55-80°F)",
    soil: "Acidic, well-drained soil",
    growth: "2-3 years to bear fruit",
    uses: "Juices, jams, baking",
    pests: "Birds, spider mites",
    propagation: "Cuttings, seeds"
  },
  {
    id: "80",
    name: "Blackberry",
    sunlight: "Full Sun",
    water: "Every 3-4 days",
    fertilizer: "Every 6 weeks",
    description: "Blackberries are fast-growing fruits with high antioxidant content.",
    image: "/images/blackberry.jpg",
    temperature: "15-29°C (59-85°F)",
    soil: "Loamy, well-drained",
    growth: "2 years to mature",
    uses: "Fresh eating, jams, desserts",
    pests: "Aphids, thrips",
    propagation: "Cuttings, root division"
  },
  {
    id: "81",
    name: "Fig",
    sunlight: "Full Sun",
    water: "Every 7 days",
    fertilizer: "Every 8 weeks",
    description: "Fig trees are drought-tolerant and produce sweet, fiber-rich fruits.",
    image: "/images/fig.jpg",
    temperature: "15-30°C (59-86°F)",
    soil: "Loamy, well-drained",
    growth: "3-5 years to fruit",
    uses: "Dried fruit, fresh consumption",
    pests: "Mealybugs, scale insects",
    propagation: "Cuttings, grafting"
  },
  {
    id: "82",
    name: "Guava",
    sunlight: "Full Sun",
    water: "Every 5 days",
    fertilizer: "Every 2 months",
    description: "Guavas are tropical fruits rich in Vitamin C and grow in warm climates.",
    image: "/images/guava.jpg",
    temperature: "20-35°C (68-95°F)",
    soil: "Sandy loam, well-drained",
    growth: "2-3 years to fruit",
    uses: "Juices, jams, fresh eating",
    pests: "Fruit flies, mealybugs",
    propagation: "Seeds, cuttings, grafting"
  },
  {
    id: "83",
    name: "Jackfruit",
    sunlight: "Full Sun",
    water: "Every 7 days",
    fertilizer: "Every 3 months",
    description: "Jackfruit is the largest fruit in the world, used in both ripe and unripe forms.",
    image: "/images/jackfruit.jpg",
    temperature: "24-35°C (75-95°F)",
    soil: "Deep, well-drained",
    growth: "3-5 years to fruit",
    uses: "Curries, desserts, chips",
    pests: "Borer insects, fruit flies",
    propagation: "Seeds, grafting"
  },
  {
    id: "84",
    name: "Lychee",
    sunlight: "Full Sun",
    water: "Every 4 days",
    fertilizer: "Every 2 months",
    description: "Lychees are small, juicy fruits with a sweet and floral flavor.",
    image: "/images/lychee.jpg",
    temperature: "20-30°C (68-86°F)",
    soil: "Sandy loam, well-drained",
    growth: "4-6 years to fruit",
    uses: "Juices, desserts, fresh consumption",
    pests: "Lychee mites, aphids",
    propagation: "Air layering, cuttings"
  },
  {
    id: "85",
    name: "Mulberry",
    sunlight: "Full Sun",
    water: "Every 3 days",
    fertilizer: "Every 6 weeks",
    description: "Mulberries are sweet, dark berries that grow well in warm climates.",
    image: "/images/mulberry.jpg",
    temperature: "20-32°C (68-90°F)",
    soil: "Loamy, well-drained",
    growth: "2-3 years to fruit",
    uses: "Juices, jams, dried fruit",
    pests: "Spider mites, whiteflies",
    propagation: "Cuttings, seeds"
  },
  {
    id: "86",
    name: "Plum",
    sunlight: "Full Sun",
    water: "Every 3-4 days",
    fertilizer: "Every 3 months",
    description: "Plums are juicy, sweet fruits that require cold winters to thrive.",
    image: "/images/plum.jpg",
    temperature: "15-28°C (59-82°F)",
    soil: "Loamy, slightly acidic",
    growth: "3-5 years to fruit",
    uses: "Jams, fresh eating, baking",
    pests: "Plum curculio, aphids",
    propagation: "Grafting, cuttings"
  },
  {
    id: "87",
    name: "Raspberry",
    sunlight: "Full Sun / Partial Shade",
    water: "Every 3 days",
    fertilizer: "Every 6 weeks",
    description: "Raspberries are soft berries that require cool winters and warm summers.",
    image: "/images/raspberry.jpg",
    temperature: "15-26°C (59-78°F)",
    soil: "Loamy, moist, well-drained",
    growth: "2 years to mature",
    uses: "Fresh eating, baking, preserves",
    pests: "Raspberry beetles, aphids",
    propagation: "Cuttings, root suckers"
  },
  {
    id: "88",
    name: "Sapodilla (Chikoo)",
    sunlight: "Full Sun",
    water: "Every 7 days",
    fertilizer: "Every 3 months",
    description: "Sapodilla, or chikoo, is a sweet, grainy-textured fruit rich in fiber.",
    image: "/images/sapodilla.jpg",
    temperature: "25-35°C (77-95°F)",
    soil: "Loamy, sandy, well-drained",
    growth: "4-5 years to fruit",
    uses: "Milkshakes, fresh eating, juices",
    pests: "Mealybugs, fruit borers",
    propagation: "Grafting, seeds"
  },
  // 🥬 Additional Leafy Vegetables
{
    id: "89",
    name: "Spinach",
    sunlight: "Partial Sun",
    water: "Every 2 days",
    fertilizer: "Every 4 weeks",
    description: "Spinach is a nutrient-rich leafy green that grows well in cool weather.",
    image: "/images/spinach.jpg",
    temperature: "10-24°C (50-75°F)",
    soil: "Well-drained, loamy soil",
    growth: "4-6 weeks",
    uses: "Salads, soups, stir-fries",
    pests: "Aphids, leaf miners",
    propagation: "Seeds"
  },
  
  {
    id: "90",
    name: "Mustard Greens",
    sunlight: "Full Sun / Partial Shade",
    water: "Every 2 days",
    fertilizer: "Every 4 weeks",
    description: "Mustard greens are peppery-tasting leaves that grow quickly in cooler weather.",
    image: "/images/mustard-greens.jpg",
    temperature: "10-24°C (50-75°F)",
    soil: "Well-drained, loamy soil",
    growth: "4-6 weeks",
    uses: "Salads, soups, stir-fries",
    pests: "Cabbage loopers, flea beetles",
    propagation: "Seeds"
  },
  {
    id: "91",
    name: "Collard Greens",
    sunlight: "Full Sun",
    water: "Every 3 days",
    fertilizer: "Every 4 weeks",
    description: "Collard greens are hardy leafy greens that thrive in warm and cool climates.",
    image: "/images/collard-greens.jpg",
    temperature: "10-29°C (50-85°F)",
    soil: "Sandy loam, well-drained",
    growth: "6-8 weeks",
    uses: "Soups, stews, stir-fries",
    pests: "Cabbage worms, aphids",
    propagation: "Seeds"
  },
  {
    id: "92",
    name: "Bok Choy",
    sunlight: "Partial Sun",
    water: "Every 2 days",
    fertilizer: "Every 3 weeks",
    description: "Bok choy is a crunchy, fast-growing Asian leafy green.",
    image: "/images/bok-choy.jpg",
    temperature: "10-24°C (50-75°F)",
    soil: "Loamy, well-drained",
    growth: "4-6 weeks",
    uses: "Stir-fries, soups, salads",
    pests: "Flea beetles, aphids",
    propagation: "Seeds"
  },
  {
    id: "93",
    name: "Arugula",
    sunlight: "Full Sun / Partial Shade",
    water: "Every 2-3 days",
    fertilizer: "Every 3 weeks",
    description: "Arugula is a spicy leafy green that grows quickly in cooler temperatures.",
    image: "/images/arugula.jpg",
    temperature: "10-24°C (50-75°F)",
    soil: "Loamy, well-drained",
    growth: "3-6 weeks",
    uses: "Salads, pizzas, sandwiches",
    pests: "Flea beetles, aphids",
    propagation: "Seeds"
  },
  {
    id: "94",
    name: "Watercress",
    sunlight: "Partial Sun",
    water: "Daily",
    fertilizer: "Every 4 weeks",
    description: "Watercress is a semi-aquatic leafy green that grows best in running water.",
    image: "/images/watercress.jpeg",
    temperature: "10-22°C (50-72°F)",
    soil: "Moist, rich, loamy soil",
    growth: "4-6 weeks",
    uses: "Salads, soups, sandwiches",
    pests: "Aphids, snails",
    propagation: "Cuttings, seeds",
},
// 🍉 Additional Fruits
{
    id: "95",
    name: "Kiwi",
    sunlight: "Full Sun",
    water: "Every 3-5 days",
    fertilizer: "Every 6 weeks",
    description: "Kiwi is a nutrient-rich fruit with a tangy-sweet taste, grown on vines.",
    image: "/images/kiwi.jpg",
    temperature: "10-25°C (50-77°F)",
    soil: "Well-drained, loamy soil",
    growth: "3-5 years",
    uses: "Juices, desserts, fresh consumption",
    pests: "Aphids, spider mites",
    propagation: "Seeds, grafting"
  },
  {
    id: "96",
    name: "Star Fruit (Carambola)",
    sunlight: "Full Sun",
    water: "Every 2-4 days",
    fertilizer: "Every 8 weeks",
    description: "Star Fruit is a tropical fruit known for its star-shaped cross-section and tangy-sweet flavor.",
    image: "/images/starfruit.jpg",
    temperature: "15-30°C (59-86°F)",
    soil: "Sandy loam, well-drained",
    growth: "3-4 years",
    uses: "Juices, salads, desserts",
    pests: "Fruit flies, aphids",
    propagation: "Seeds, grafting"
  },
  {
    id: "97",
    name: "Water Apple (Rose Apple)",
    sunlight: "Full Sun",
    water: "Every 3-5 days",
    fertilizer: "Every 2 months",
    description: "Water Apple is a tropical fruit with a crisp texture and mild sweetness.",
    image: "/images/water-apple.jpg",
    temperature: "20-35°C (68-95°F)",
    soil: "Moist, well-drained loam",
    growth: "2-3 years",
    uses: "Juices, fresh consumption, jams",
    pests: "Mealybugs, fruit flies",
    propagation: "Seeds, air-layering"
  },
  {
    id: "98",
    name: "Palm Fruit",
    sunlight: "Full Sun",
    water: "Weekly",
    fertilizer: "Every 6 months",
    description: "Palm fruit is a high-energy tropical fruit harvested from palm trees.",
    image: "/images/palm-fruit.jpg",
    temperature: "22-35°C (72-95°F)",
    soil: "Sandy, well-drained soil",
    growth: "5-10 years",
    uses: "Oils, food, beverages",
    pests: "Palm weevils, scale insects",
    propagation: "Seeds"
  },
  {
    id: "99",
    name: "Mangosteen",
    sunlight: "Partial to Full Sun",
    water: "Every 2-3 days",
    fertilizer: "Every 2 months",
    description: "Mangosteen is a tropical fruit known as the 'Queen of Fruits' due to its sweet, tangy taste and health benefits.",
    image: "/images/mangosteen.jpg",
    temperature: "25-35°C (77-95°F)",
    soil: "Well-drained, rich organic soil",
    growth: "8-10 years",
    uses: "Fresh consumption, juices, desserts, medicinal purposes",
    pests: "Fruit flies, scale insects",
    propagation: "Seeds, grafting"
  },
  {
    id: "100",
    name: "Custard Apple",
    sunlight: "Full Sun",
    water: "Every 3-4 days",
    fertilizer: "Every 6 weeks",
    description: "Custard Apple, also known as Sugar Apple or Sitaphal, is a tropical fruit known for its creamy texture and sweet flavor.",
    image: "/images/custard-apple.jpg",
    temperature: "25-35°C (77-95°F)",
    soil: "Well-drained, sandy loam soil",
    growth: "3-5 years",
    uses: "Fresh consumption, milkshakes, ice creams, medicinal purposes",
    pests: "Mealybugs, aphids, fruit borers",
    propagation: "Seeds, grafting, air-layering"
  },
  {
    id: "101",
    name: "Açaí",
    sunlight: "Full Sun to Partial Shade",
    water: "Moderate, requires consistent moisture",
    fertilizer: "Every 2 months with organic compost",
    description: "Açaí berries grow on tall, slender palm trees native to the Amazon rainforest. They are highly valued for their antioxidant-rich properties and are often used in health foods.",
    image: "/images/acai.jpg",
    temperature: "25-30°C (77-86°F)",
    soil: "Well-drained, sandy loam, rich in organic matter",
    growth: "3-5 years for fruit production",
    uses: "Smoothie bowls, juices, health supplements, ice creams",
    pests: "Weevils, aphids, fungal infections",
    propagation: "Seeds, suckers, and tissue culture"
  },
  {
    id: "102",
    name: "Cashew Apple",
    sunlight: "Full Sun",
    water: "Moderate, drought-resistant once established",
    fertilizer: "Every 3 months with balanced NPK fertilizer",
    description: "The cashew apple is the swollen fruit of the cashew tree, known for its juicy, sweet, and tangy flavor. It is rich in Vitamin C and is used in juices, jams, and fermented beverages.",
    image: "/images/cashew-apple.jpg",
    temperature: "25-35°C (77-95°F)",
    soil: "Well-drained sandy or loamy soil",
    growth: "3-5 years for fruit production",
    uses: "Juices, jams, alcoholic beverages, and pickles",
    pests: "Fruit flies, aphids, powdery mildew",
    propagation: "Seeds, air layering, and grafting"
  },
];

export default plants;